In [1]:
import pandas as pd
import numpy as np

C:\Users\Jay\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED


In [2]:
raw_data = pd.read_csv("Absenteeism-data.csv", delimiter=',')
raw_data

ID  Reason for Absence        Date  Transportation Expense  \
0    11                  26  07/07/2015                     289   
1    36                   0  14/07/2015                     118   
2     3                  23  15/07/2015                     179   
3     7                   7  16/07/2015                     279   
4    11                  23  23/07/2015                     289   
..   ..                 ...         ...                     ...   
695  17                  10  23/05/2018                     179   
696  28                   6  23/05/2018                     225   
697  18                  10  24/05/2018                     330   
698  25                  23  24/05/2018                     235   
699  15                  28  31/05/2018                     291   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30   
1                  13   50                  239.554               31   
2                  51   38                  239.554               31   
3                   5   39                  239.554               24   
4                  36   33                  239.554               30   
..                ...  ...                      ...              ...   
695                22   40                  237.656               22   
696                26   28                  237.656               24   
697                16   28                  237.656               25   
698                16   32                  237.656               25   
699                31   40                  237.656               25   

     Education  Children  Pets  Absenteeism Time in Hours  
0            1         2     1                          4  
1            1         1     0                          0  
2            1         0     0                          2  
3            1         2     0                          4  
4            1         2     1                          2  
..         ...       ...   ...                        ...  
695          2         2     0                          8  
696          1         1     2                          3  
697          2         0     0                          8  
698          3         0     0                          2  
699          1         1     1                          2  

[700 rows x 12 columns]

In [3]:
df = raw_data.copy()
df

ID  Reason for Absence        Date  Transportation Expense  \
0    11                  26  07/07/2015                     289   
1    36                   0  14/07/2015                     118   
2     3                  23  15/07/2015                     179   
3     7                   7  16/07/2015                     279   
4    11                  23  23/07/2015                     289   
..   ..                 ...         ...                     ...   
695  17                  10  23/05/2018                     179   
696  28                   6  23/05/2018                     225   
697  18                  10  24/05/2018                     330   
698  25                  23  24/05/2018                     235   
699  15                  28  31/05/2018                     291   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30   
1                  13   50                  239.554               31   
2                  51   38                  239.554               31   
3                   5   39                  239.554               24   
4                  36   33                  239.554               30   
..                ...  ...                      ...              ...   
695                22   40                  237.656               22   
696                26   28                  237.656               24   
697                16   28                  237.656               25   
698                16   32                  237.656               25   
699                31   40                  237.656               25   

     Education  Children  Pets  Absenteeism Time in Hours  
0            1         2     1                          4  
1            1         1     0                          0  
2            1         0     0                          2  
3            1         2     0                          4  
4            1         2     1                          2  
..         ...       ...   ...                        ...  
695          2         2     0                          8  
696          1         1     2                          3  
697          2         0     0                          8  
698          3         0     0                          2  
699          1         1     1                          2  

[700 rows x 12 columns]

# Drop ID column 

In [4]:
df=df.drop("ID",axis=1)
df

Reason for Absence        Date  Transportation Expense  Distance to Work  \
0                    26  07/07/2015                     289                36   
1                     0  14/07/2015                     118                13   
2                    23  15/07/2015                     179                51   
3                     7  16/07/2015                     279                 5   
4                    23  23/07/2015                     289                36   
..                  ...         ...                     ...               ...   
695                  10  23/05/2018                     179                22   
696                   6  23/05/2018                     225                26   
697                  10  24/05/2018                     330                16   
698                  23  24/05/2018                     235                16   
699                  28  31/05/2018                     291                31   

     Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0     33                  239.554               30          1         2     1   
1     50                  239.554               31          1         1     0   
2     38                  239.554               31          1         0     0   
3     39                  239.554               24          1         2     0   
4     33                  239.554               30          1         2     1   
..   ...                      ...              ...        ...       ...   ...   
695   40                  237.656               22          2         2     0   
696   28                  237.656               24          1         1     2   
697   28                  237.656               25          2         0     0   
698   32                  237.656               25          3         0     0   
699   40                  237.656               25          1         1     1   

     Absenteeism Time in Hours  
0                            4  
1                            0  
2                            2  
3                            4  
4                            2  
..                         ...  
695                          8  
696                          3  
697                          8  
698                          2  
699                          2  

[700 rows x 11 columns]

# Replace Reason for Absence with appropriate groups 

In [5]:
np.sort(df["Reason for Absence"].unique())

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28], dtype=int64)

In [6]:
np.unique(df["Reason for Absence"],return_counts=True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28], dtype=int64),
 array([ 38,  16,   1,   1,   2,   3,   6,  13,   5,   4,  22,  24,   8,
         52,  18,   2,   3,   1,  21,  36,   6,  32, 147,   3,  29,  31,
         66, 110], dtype=int64))

In [7]:
reason_columns = pd.get_dummies(df["Reason for Absence"])
reason_columns

0      1      2      3      4      5      6      7      8      9   \
0    False  False  False  False  False  False  False  False  False  False   
1     True  False  False  False  False  False  False  False  False  False   
2    False  False  False  False  False  False  False  False  False  False   
3    False  False  False  False  False  False  False   True  False  False   
4    False  False  False  False  False  False  False  False  False  False   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
695  False  False  False  False  False  False  False  False  False  False   
696  False  False  False  False  False  False   True  False  False  False   
697  False  False  False  False  False  False  False  False  False  False   
698  False  False  False  False  False  False  False  False  False  False   
699  False  False  False  False  False  False  False  False  False  False   

     ...     18     19     21     22     23     24     25     26     27     28  
0    ...  False  False  False  False  False  False  False   True  False  False  
1    ...  False  False  False  False  False  False  False  False  False  False  
2    ...  False  False  False  False   True  False  False  False  False  False  
3    ...  False  False  False  False  False  False  False  False  False  False  
4    ...  False  False  False  False   True  False  False  False  False  False  
..   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
695  ...  False  False  False  False  False  False  False  False  False  False  
696  ...  False  False  False  False  False  False  False  False  False  False  
697  ...  False  False  False  False  False  False  False  False  False  False  
698  ...  False  False  False  False   True  False  False  False  False  False  
699  ...  False  False  False  False  False  False  False  False  False   True  

[700 rows x 28 columns]

In [8]:
# type(reason_columns)
reason_columns.shape[0]


700

In [9]:
reason_columns["check"] = reason_columns.sum(axis=1)

In [10]:
reason_columns["check"].unique(), reason_columns["check"].sum()

(array([1], dtype=int64), 700)

In [11]:
reason_columns.drop([0],axis=1,inplace=True)

In [12]:
reason_columns.loc[:,1:14].max(axis=1).astype(dtype=int)

0      0
1      0
2      0
3      1
4      0
      ..
695    1
696    1
697    1
698    0
699    0
Length: 700, dtype: int32

In [13]:
reason_columns.drop(["check"],axis=1,inplace=True)

In [14]:
reason_group_1.sum(),reason_group_2.sum(),reason_group_3.sum(),reason_group_4.sum()

NameError: name 'reason_group_1' is not defined

In [18]:
type(reason_columns.loc[0,1:])

pandas.core.series.Series

In [25]:
df.iloc[0,1:]

Date                         07/07/2015
Transportation Expense              289
Distance to Work                     36
Age                                  33
Daily Work Load Average         239.554
Body Mass Index                      30
Education                             1
Children                              2
Pets                                  1
Absenteeism Time in Hours             4
Name: 0, dtype: object

In [31]:
help(pd.DataFrame.drop_duplicates)

Help on function drop_duplicates in module pandas.core.frame:

drop_duplicates(self, subset: 'Hashable | Sequence[Hashable] | None' = None, *, keep: 'DropKeep' = 'first', inplace: 'bool' = False, ignore_index: 'bool' = False) -> 'DataFrame | None'
    Return DataFrame with duplicate rows removed.
    
    Considering certain columns is optional. Indexes, including time indexes
    are ignored.
    
    Parameters
    ----------
    subset : column label or sequence of labels, optional
        Only consider certain columns for identifying duplicates, by
        default use all of the columns.
    keep : {'first', 'last', ``False``}, default 'first'
        Determines which duplicates (if any) to keep.
    
        - 'first' : Drop duplicates except for the first occurrence.
        - 'last' : Drop duplicates except for the last occurrence.
        - ``False`` : Drop all duplicates.
    
    inplace : bool, default ``False``
        Whether to modify the DataFrame rather than creating a 

In [15]:
reason_group_1 = reason_columns.loc[:,1:14].max(axis=1).astype(dtype=int)
reason_group_2 = reason_columns.loc[:,15:17].max(axis=1).astype(dtype=int)
reason_group_3 = reason_columns.loc[:,18:21].max(axis=1).astype(dtype=int)
reason_group_4 = reason_columns.loc[:,22:].max(axis=1).astype(dtype=int)

In [ ]:
reason_group_1,reason_group_2,reason_group_3,reason_group_4

In [ ]:
df.drop(["Reason for Absence"],axis=1,inplace=True)

In [ ]:
df = pd.concat([df,reason_group_1,reason_group_2,reason_group_3,reason_group_4],axis =1)

In [ ]:
df.columns = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_Group_1', 'Reason_Group_2', 'Reason_Group_3', 'Reason_Group_4']

In [ ]:
df

#    Checkpoint

In [ ]:
df_1 = df.copy()
df_1

# Extracting Month 

In [ ]:
type(df_1["Date"][0])

In [ ]:
df_1["Date"]=pd.to_datetime(df_1["Date"],dayfirst=True)

In [ ]:
month = df_1.loc[:,"Date"].dt.month

In [ ]:
month

In [ ]:
df_1=pd.concat([df_1,month],axis=1)

In [ ]:
df_1.columns.values

In [ ]:
df_1.columns=['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_Group_1',
       'Reason_Group_2', 'Reason_Group_3', 'Reason_Group_4', 'Month']

In [ ]:
def date_to_weekday(date_value):
    return date_value.weekday()

In [ ]:
df_1["DOW"] = df_1["Date"].apply(date_to_weekday)

In [ ]:
df_1

In [ ]:
df_1.drop(["Date"],axis=1,inplace=True)

In [ ]:
df_1.columns=['Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_Group_1',
       'Reason_Group_2', 'Reason_Group_3', 'Reason_Group_4', 'Month',
       'Weekday']

# Checkpoint 2 

In [ ]:
df_2 = df_1.copy()
df_2

# Modifying Education column 

In [ ]:
df_2["Education"] = df_2["Education"].map({1:0,2:1,3:1,4:1})

In [ ]:
df_2["Education"].unique(), df_1["Education"].unique()

In [ ]:
raw_data

# Regrouping and saving csv file 

In [ ]:
df_2.columns.values

In [ ]:
columns_reordered = ['Reason_Group_1',
       'Reason_Group_2', 'Reason_Group_3', 'Reason_Group_4', 'Month',
       'Weekday','Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

In [ ]:
df_2 = df_2[columns_reordered]

In [ ]:
df_2

In [ ]:
df_final = df_2.copy()

In [ ]:
df_final.to_csv("Absenteeism-Data-Preprocessed.csv",sep=',')